package entities

type ItemGet struct {
	ItemIDs             []string            `json:"itemids,omitempty"`
	GroupIDs            []string            `json:"groupids,omitempty"`
	TemplateIDs         []string            `json:"templateids,omitempty"`
	HostIDs             []string            `json:"hostids,omitempty"`
	ProxyIDs            []string            `json:"proxyids,omitempty"`
	InterfaceIDs        []string            `json:"interfaceids,omitempty"`
	GraphIDS            []string            `json:"graphids,omitempty"`
	TriggerIDs          []string            `json:"triggerids,omitempty"`
	WebItems            string              `json:"webitems,omitempty"`
	Inherited           bool                `json:"inherited,omitempty"`
	Templated           bool                `json:"templated,omitempty"`
	Monitored           bool                `json:"monitored,omitempty"`
	Group               string              `json:"group,omitempty"`
	Host                string              `json:"host,omitempty"`
	EvalType            int                 `json:"evaltype,omitempty"`
	Tags                []map[string]string `json:"tags,omitempty"`
	WithTriggers        bool                `json:"with_triggers,omitempty"`
	SelectHosts         string              `json:"selectHosts,omitempty"`
	SelectInterfaces    string              `json:"selectInterfaces,omitempty"`
	SelectTriggers      string              `json:"selectTriggers,omitempty"`
	SelectGraphs        string              `json:"selectGraphs,omitempty"`
	SelectTags          string              `json:"selectTags,omitempty"`
	SelectDiscoveryRule string              `json:"selectDiscoveryRule,omitempty"`
	SelectItemDiscovery string              `json:"selectItemDiscovery,omitempty"`
	SelectPreprocessing string              `json:"selectPreprocessing,omitempty"`
	ZabbixCommun
}

type ItemCreate struct {
	Tags            []ZabbixTag         `json:"tags,omitempty"`
	PreProcessing   []ItemPreprocessing `json:"preprocessing,omitempty"`
	Delay           string              `json:"delay,omitempty"`
	HostID          string              `json:"hostid,omitempty"`
	InterfaceID     string              `json:"interfaceid,omitempty"`
	Key             string              `json:"key_,omitempty"`
	Name            string              `json:"name,omitempty"`
	Type            int                 `json:"type,omitempty"`
	Url             string              `json:"url,omitempty"`
	ValueType       int                 `json:"value_type,omitempty"`
	AllowTraps      int                 `json:"allow_traps,omitempty"`
	AuthType        int                 `json:"auth_type,omitempty"`
	Description     string              `json:"description,omitempty"`
	Error           string              `json:"error,omitempty"`
	Flags           int                 `json:"flags,omitempty"`
	FollowRedirects int                 `json:"follow_redirects,omitempty"`
	Headers         map[string]string   `json:"headers,omitempty"`
	History         string              `json:"history,omitempty"`
	HttpProxy       string              `json:"http_proxy,omitempty"`
	InventoryLink   int                 `json:"inventory_link,omitempty"`
	IPMISensor      string              `json:"ipmi_sensor,omitempty"`
	JmxEndpoint     string              `json:"jmx_endpoint,omitempty"`
	LastClock       string              `json:"lastclock,omitempty"`
	LastNS          int                 `json:"lastns,omitempty"`
	LastValue       string              `json:"lastvalue,omitempty"`
	LogTimeFmt      string              `json:"logtimefmt,omitempty"`
	MasterItemID    int                 `json:"master_itemid,omitempty"`
	OutputFormat    int                 `json:"output_format,omitempty"`
	Params          string              `json:"params,omitempty"`
	Parameters      []map[string]string `json:"parameters,omitempty"`
	Password        string              `json:"password,omitempty"`
	PostType        int                 `json:"post_type,omitempty"`
	Posts           string              `json:"posts,omitempty"`
	PrevValue       string              `json:"prevvalue,omitempty"`
	PrivateKey      string              `json:"privatekey,omitempty"`
	PublicKey       string              `json:"publickey,omitempty"`
	QueryFIelds     []string            `json:"query_fields,omitempty"`
	RequestMethod   int                 `json:"request_method,omitempty"`
	RetrievMode     int                 `json:"retriev_mode,omitempty"`
	SNMPOid         string              `json:"snmp_oid,omitempty"`
	SSLCertFile     string              `json:"ssl_cert_file,omitempty"`
	SSLKeyFile      string              `json:"ssl_key_file,omitempty"`
	SSLKeyPassword  string              `json:"ssl_key_password,omitempty"`
	State           int                 `json:"state,omitempty"`
	Status          int                 `json:"status,omitempty"`
	StatusCode      string              `json:"status_code,omitempty"`
	TemplateID      string              `json:"templateid,omitempty"`
	Timeout         string              `json:"timeout,omitempty"`
	TrapperHosts    string              `json:"trapper_hosts,omitempty"`
	Trends          string              `json:"trends,omitempty"`
	Units           string              `json:"units,omitempty"`
	Username        string              `json:"username,omitempty"`
	UUID            string              `json:"uuid,omitempty"`
	ValuemapID      string              `json:"valuemapid,omitempty"`
	VerifyHost      int                 `json:"verify_host,omitempty"`
	VerifyPeer      int                 `json:"verify_peer,omitempty"`
}

type ItemUpdate struct {
	ItemID          string              `json:"itemid,omitempty"`
	Tags            []ZabbixTag         `json:"tags,omitempty"`
	PreProcessing   []ItemPreprocessing `json:"preprocessing,omitempty"`
	Delay           string              `json:"delay,omitempty"`
	HostID          string              `json:"hostid,omitempty"`
	InterfaceID     string              `json:"interfaceid,omitempty"`
	Key             string              `json:"key_,omitempty"`
	Name            string              `json:"name,omitempty"`
	Type            int                 `json:"type,omitempty"`
	Url             string              `json:"url,omitempty"`
	ValueType       int                 `json:"value_type,omitempty"`
	AllowTraps      int                 `json:"allow_traps,omitempty"`
	AuthType        int                 `json:"auth_type,omitempty"`
	Description     string              `json:"description,omitempty"`
	Error           string              `json:"error,omitempty"`
	Flags           int                 `json:"flags,omitempty"`
	FollowRedirects int                 `json:"follow_redirects,omitempty"`
	Headers         map[string]string   `json:"headers,omitempty"`
	History         string              `json:"history,omitempty"`
	HttpProxy       string              `json:"http_proxy,omitempty"`
	InventoryLink   int                 `json:"inventory_link,omitempty"`
	IPMISensor      string              `json:"ipmi_sensor,omitempty"`
	JmxEndpoint     string              `json:"jmx_endpoint,omitempty"`
	LastClock       string              `json:"lastclock,omitempty"`
	LastNS          int                 `json:"lastns,omitempty"`
	LastValue       string              `json:"lastvalue,omitempty"`
	LogTimeFmt      string              `json:"logtimefmt,omitempty"`
	MasterItemID    int                 `json:"master_itemid,omitempty"`
	OutputFormat    int                 `json:"output_format,omitempty"`
	Params          string              `json:"params,omitempty"`
	Parameters      []map[string]string `json:"parameters,omitempty"`
	Password        string              `json:"password,omitempty"`
	PostType        int                 `json:"post_type,omitempty"`
	Posts           string              `json:"posts,omitempty"`
	PrevValue       string              `json:"prevvalue,omitempty"`
	PrivateKey      string              `json:"privatekey,omitempty"`
	PublicKey       string              `json:"publickey,omitempty"`
	QueryFIelds     []string            `json:"query_fields,omitempty"`
	RequestMethod   int                 `json:"request_method,omitempty"`
	RetrievMode     int                 `json:"retriev_mode,omitempty"`
	SNMPOid         string              `json:"snmp_oid,omitempty"`
	SSLCertFile     string              `json:"ssl_cert_file,omitempty"`
	SSLKeyFile      string              `json:"ssl_key_file,omitempty"`
	SSLKeyPassword  string              `json:"ssl_key_password,omitempty"`
	State           int                 `json:"state,omitempty"`
	Status          int                 `json:"status,omitempty"`
	StatusCode      string              `json:"status_code,omitempty"`
	TemplateID      string              `json:"templateid,omitempty"`
	Timeout         string              `json:"timeout,omitempty"`
	TrapperHosts    string              `json:"trapper_hosts,omitempty"`
	Trends          string              `json:"trends,omitempty"`
	Units           string              `json:"units,omitempty"`
	Username        string              `json:"username,omitempty"`
	UUID            string              `json:"uuid,omitempty"`
	ValuemapID      string              `json:"valuemapid,omitempty"`
	VerifyHost      int                 `json:"verify_host,omitempty"`
	VerifyPeer      int                 `json:"verify_peer,omitempty"`
}

type ItemObject struct {
	ItemID          string              `json:"itemid,omitempty"`
	Delay           string              `json:"delay,omitempty"`
	HostID          string              `json:"hostid,omitempty"`
	InterfaceID     string              `json:"interfaceid,omitempty"`
	Key             string              `json:"key_,omitempty"`
	Name            string              `json:"name,omitempty"`
	Type            int                 `json:"type,omitempty"`
	Url             string              `json:"url,omitempty"`
	ValueType       int                 `json:"value_type,omitempty"`
	AllowTraps      int                 `json:"allow_traps,omitempty"`
	AuthType        int                 `json:"auth_type,omitempty"`
	Description     string              `json:"description,omitempty"`
	Error           string              `json:"error,omitempty"`
	Flags           int                 `json:"flags,omitempty"`
	FollowRedirects int                 `json:"follow_redirects,omitempty"`
	Headers         map[string]string   `json:"headers,omitempty"`
	History         string              `json:"history,omitempty"`
	HttpProxy       string              `json:"http_proxy,omitempty"`
	InventoryLink   int                 `json:"inventory_link,omitempty"`
	IPMISensor      string              `json:"ipmi_sensor,omitempty"`
	JmxEndpoint     string              `json:"jmx_endpoint,omitempty"`
	LastClock       string              `json:"lastclock,omitempty"`
	LastNS          int                 `json:"lastns,omitempty"`
	LastValue       string              `json:"lastvalue,omitempty"`
	LogTimeFmt      string              `json:"logtimefmt,omitempty"`
	MasterItemID    int                 `json:"master_itemid,omitempty"`
	OutputFormat    int                 `json:"output_format,omitempty"`
	Params          string              `json:"params,omitempty"`
	Parameters      []map[string]string `json:"parameters,omitempty"`
	Password        string              `json:"password,omitempty"`
	PostType        int                 `json:"post_type,omitempty"`
	Posts           string              `json:"posts,omitempty"`
	PrevValue       string              `json:"prevvalue,omitempty"`
	PrivateKey      string              `json:"privatekey,omitempty"`
	PublicKey       string              `json:"publickey,omitempty"`
	QueryFIelds     []string            `json:"query_fields,omitempty"`
	RequestMethod   int                 `json:"request_method,omitempty"`
	RetrievMode     int                 `json:"retriev_mode,omitempty"`
	SNMPOid         string              `json:"snmp_oid,omitempty"`
	SSLCertFile     string              `json:"ssl_cert_file,omitempty"`
	SSLKeyFile      string              `json:"ssl_key_file,omitempty"`
	SSLKeyPassword  string              `json:"ssl_key_password,omitempty"`
	State           int                 `json:"state,omitempty"`
	Status          int                 `json:"status,omitempty"`
	StatusCode      string              `json:"status_code,omitempty"`
	TemplateID      string              `json:"templateid,omitempty"`
	Timeout         string              `json:"timeout,omitempty"`
	TrapperHosts    string              `json:"trapper_hosts,omitempty"`
	Trends          string              `json:"trends,omitempty"`
	Units           string              `json:"units,omitempty"`
	Username        string              `json:"username,omitempty"`
	UUID            string              `json:"uuid,omitempty"`
	ValuemapID      string              `json:"valuemapid,omitempty"`
	VerifyHost      int                 `json:"verify_host,omitempty"`
	VerifyPeer      int                 `json:"verify_peer,omitempty"`
}

type ItemPreprocessing struct {
	Type               int    `json:"type,omitempty"`
	Params             string `json:"params,omitempty"`
	ErrorHandler       int    `json:"error_handler,omitempty"`
	ErrorHandlerParams string `json:"error_handler_params,omitempty"`
}

type ItemResponse struct {
	ItemIDs []string `json:"itemids"`
}
