package entities

type ItemGet struct {
	ItemIDs             []string            `json:"itemids,omitempty"`
	GroupIDs            []string            `json:"groupids,omitempty"`
	TemplateIDs         []string            `json:"templateids,omitempty"`
	HostIDs             []string            `json:"hostids,omitempty"`
	ProxyIDs            []string            `json:"proxyids,omitempty"`
	InterfaceIDs        []string            `json:"interfaceids,omitempty"`
	GraphIDS            []string            `json:"graphids,omitempty"`
	TriggerIDs          []string            `json:"triggerids,omitempty"`
	WebItems            string              `json:"webitems,omitempty"`
	Inherited           bool                `json:"inherited,omitempty"`
	Templated           bool                `json:"templated,omitempty"`
	Monitored           bool                `json:"monitored,omitempty"`
	Group               string              `json:"group,omitempty"`
	Host                string              `json:"host,omitempty"`
	EvalType            int                 `json:"evaltype,omitempty"`
	Tags                []map[string]string `json:"tags,omitempty"`
	WithTriggers        bool                `json:"with_triggers,omitempty"`
	SelectHosts         string              `json:"selectHosts,omitempty"`
	SelectInterfaces    string              `json:"selectInterfaces,omitempty"`
	SelectTriggers      string              `json:"selectTriggers,omitempty"`
	SelectGraphs        string              `json:"selectGraphs,omitempty"`
	SelectTags          string              `json:"selectTags,omitempty"`
	SelectDiscoveryRule string              `json:"selectDiscoveryRule,omitempty"`
	SelectItemDiscovery string              `json:"selectItemDiscovery,omitempty"`
	SelectPreprocessing string              `json:"selectPreprocessing,omitempty"`
	ZabbixCommun
}

type ItemCreate struct {
	Tags            []ZabbixTag         `json:"tags"`
	PreProcessing   []ItemPreprocessing `json:"preprocessing"`
	Delay           string              `json:"delay"`
	HostID          string              `json:"hostid"`
	InterfaceID     string              `json:"interfaceid"`
	Key             string              `json:"key_"`
	Name            string              `json:"name"`
	Type            int                 `json:"type"`
	Url             string              `json:"url"`
	ValueType       int                 `json:"value_type"`
	AllowTraps      int                 `json:"allow_traps"`
	AuthType        int                 `json:"auth_type"`
	Description     string              `json:"description"`
	Error           string              `json:"error"`
	Flags           int                 `json:"flags"`
	FollowRedirects int                 `json:"follow_redirects"`
	Headers         map[string]string   `json:"headers"`
	History         string              `json:"history"`
	HttpProxy       string              `json:"http_proxy"`
	InventoryLink   int                 `json:"inventory_link"`
	IPMISensor      string              `json:"ipmi_sensor"`
	JmxEndpoint     string              `json:"jmx_endpoint"`
	LastClock       string              `json:"lastclock"`
	LastNS          int                 `json:"lastns"`
	LastValue       string              `json:"lastvalue"`
	LogTimeFmt      string              `json:"logtimefmt"`
	MasterItemID    int                 `json:"master_itemid"`
	OutputFormat    int                 `json:"output_format"`
	Params          string              `json:"params"`
	Parameters      []map[string]string `json:"parameters"`
	Password        string              `json:"password"`
	PostType        int                 `json:"post_type"`
	Posts           string              `json:"posts"`
	PrevValue       string              `json:"prevvalue"`
	PrivateKey      string              `json:"privatekey"`
	PublicKey       string              `json:"publickey"`
	QueryFIelds     []string            `json:"query_fields"`
	RequestMethod   int                 `json:"request_method"`
	RetrievMode     int                 `json:"retriev_mode"`
	SNMPOid         string              `json:"snmp_oid"`
	SSLCertFile     string              `json:"ssl_cert_file"`
	SSLKeyFile      string              `json:"ssl_key_file"`
	SSLKeyPassword  string              `json:"ssl_key_password"`
	State           int                 `json:"state"`
	Status          int                 `json:"status"`
	StatusCode      string              `json:"status_code"`
	TemplateID      string              `json:"templateid"`
	Timeout         string              `json:"timeout"`
	TrapperHosts    string              `json:"trapper_hosts"`
	Trends          string              `json:"trends"`
	Units           string              `json:"units"`
	Username        string              `json:"username"`
	UUID            string              `json:"uuid"`
	ValuemapID      string              `json:"valuemapid"`
	VerifyHost      int                 `json:"verify_host"`
	VerifyPeer      int                 `json:"verify_peer"`
}

type ItemUpdate struct {
	ItemID          string              `json:"itemid"`
	Tags            []ZabbixTag         `json:"tags"`
	PreProcessing   []ItemPreprocessing `json:"preprocessing"`
	Delay           string              `json:"delay"`
	HostID          string              `json:"hostid"`
	InterfaceID     string              `json:"interfaceid"`
	Key             string              `json:"key_"`
	Name            string              `json:"name"`
	Type            int                 `json:"type"`
	Url             string              `json:"url"`
	ValueType       int                 `json:"value_type"`
	AllowTraps      int                 `json:"allow_traps"`
	AuthType        int                 `json:"auth_type"`
	Description     string              `json:"description"`
	Error           string              `json:"error"`
	Flags           int                 `json:"flags"`
	FollowRedirects int                 `json:"follow_redirects"`
	Headers         map[string]string   `json:"headers"`
	History         string              `json:"history"`
	HttpProxy       string              `json:"http_proxy"`
	InventoryLink   int                 `json:"inventory_link"`
	IPMISensor      string              `json:"ipmi_sensor"`
	JmxEndpoint     string              `json:"jmx_endpoint"`
	LastClock       string              `json:"lastclock"`
	LastNS          int                 `json:"lastns"`
	LastValue       string              `json:"lastvalue"`
	LogTimeFmt      string              `json:"logtimefmt"`
	MasterItemID    int                 `json:"master_itemid"`
	OutputFormat    int                 `json:"output_format"`
	Params          string              `json:"params"`
	Parameters      []map[string]string `json:"parameters"`
	Password        string              `json:"password"`
	PostType        int                 `json:"post_type"`
	Posts           string              `json:"posts"`
	PrevValue       string              `json:"prevvalue"`
	PrivateKey      string              `json:"privatekey"`
	PublicKey       string              `json:"publickey"`
	QueryFIelds     []string            `json:"query_fields"`
	RequestMethod   int                 `json:"request_method"`
	RetrievMode     int                 `json:"retriev_mode"`
	SNMPOid         string              `json:"snmp_oid"`
	SSLCertFile     string              `json:"ssl_cert_file"`
	SSLKeyFile      string              `json:"ssl_key_file"`
	SSLKeyPassword  string              `json:"ssl_key_password"`
	State           int                 `json:"state"`
	Status          int                 `json:"status"`
	StatusCode      string              `json:"status_code"`
	TemplateID      string              `json:"templateid"`
	Timeout         string              `json:"timeout"`
	TrapperHosts    string              `json:"trapper_hosts"`
	Trends          string              `json:"trends"`
	Units           string              `json:"units"`
	Username        string              `json:"username"`
	UUID            string              `json:"uuid"`
	ValuemapID      string              `json:"valuemapid"`
	VerifyHost      int                 `json:"verify_host"`
	VerifyPeer      int                 `json:"verify_peer"`
}

type ItemObject struct {
	ItemID          string              `json:"itemid"`
	Delay           string              `json:"delay"`
	HostID          string              `json:"hostid"`
	InterfaceID     string              `json:"interfaceid"`
	Key             string              `json:"key_"`
	Name            string              `json:"name"`
	Type            int                 `json:"type"`
	Url             string              `json:"url"`
	ValueType       int                 `json:"value_type"`
	AllowTraps      int                 `json:"allow_traps"`
	AuthType        int                 `json:"auth_type"`
	Description     string              `json:"description"`
	Error           string              `json:"error"`
	Flags           int                 `json:"flags"`
	FollowRedirects int                 `json:"follow_redirects"`
	Headers         map[string]string   `json:"headers"`
	History         string              `json:"history"`
	HttpProxy       string              `json:"http_proxy"`
	InventoryLink   int                 `json:"inventory_link"`
	IPMISensor      string              `json:"ipmi_sensor"`
	JmxEndpoint     string              `json:"jmx_endpoint"`
	LastClock       string              `json:"lastclock"`
	LastNS          int                 `json:"lastns"`
	LastValue       string              `json:"lastvalue"`
	LogTimeFmt      string              `json:"logtimefmt"`
	MasterItemID    int                 `json:"master_itemid"`
	OutputFormat    int                 `json:"output_format"`
	Params          string              `json:"params"`
	Parameters      []map[string]string `json:"parameters"`
	Password        string              `json:"password"`
	PostType        int                 `json:"post_type"`
	Posts           string              `json:"posts"`
	PrevValue       string              `json:"prevvalue"`
	PrivateKey      string              `json:"privatekey"`
	PublicKey       string              `json:"publickey"`
	QueryFIelds     []string            `json:"query_fields"`
	RequestMethod   int                 `json:"request_method"`
	RetrievMode     int                 `json:"retriev_mode"`
	SNMPOid         string              `json:"snmp_oid"`
	SSLCertFile     string              `json:"ssl_cert_file"`
	SSLKeyFile      string              `json:"ssl_key_file"`
	SSLKeyPassword  string              `json:"ssl_key_password"`
	State           int                 `json:"state"`
	Status          int                 `json:"status"`
	StatusCode      string              `json:"status_code"`
	TemplateID      string              `json:"templateid"`
	Timeout         string              `json:"timeout"`
	TrapperHosts    string              `json:"trapper_hosts"`
	Trends          string              `json:"trends"`
	Units           string              `json:"units"`
	Username        string              `json:"username"`
	UUID            string              `json:"uuid"`
	ValuemapID      string              `json:"valuemapid"`
	VerifyHost      int                 `json:"verify_host"`
	VerifyPeer      int                 `json:"verify_peer"`
}

type ItemPreprocessing struct {
	Type               int    `json:"type"`
	Params             string `json:"params"`
	ErrorHandler       int    `json:"error_handler"`
	ErrorHandlerParams string `json:"error_handler_params"`
}
